language: python
cache: pip
dist: xenial
python:
    - '2.7'
    - '3.4'
    - '3.5'
    - '3.6'
    - '3.7'

install:
    - pip install -r requirements.txt
script:
    nosetests --nocapture test_alpha_vantage/test_alphavantage.py
after_sucess:
    codecov